### ISSUE TITLE
inputFormField，在view模式下RightAddon不显示

### ISSUE THREAD

**Issue by qq7892326** [uxcore/uxcore-form#101]
inputFormField中，如果在RightAddon中设置了单位（例如：元、月 等），切换到Constants.MODE.VIEW下查看表单项的时候，RightAddon应该显示出来，，例如填写的是6个月，如果“月”不显示而只显示6的话，，用户不知道具体是6天还是6个月还是6年~

**Comment by eternalsky** [comment]
rightAddon 的作用只是为了一些装饰物，而这些装饰物往往是只有编辑模式下需要的，所以不可能带到 view 模式下来。但是可以考虑提供一种 view 模式下的渲染回调，可以自定义渲染的样式。

**Comment by eternalsky** [comment]
add renderView prop in InputFormField see https://github.com/uxcore/uxcore-input-form-field/commit/1d737bc0bc1b4802cb0e4c81cb1e80f63bbcb243
