### ISSUE TITLE
SearchFormField设置jsxlabel属性不生效

### ISSUE THREAD

**Issue by wushanchao** [uxcore/uxcore-form#106]
示例代码地址在这，
http://codepen.io/samwu/pen/RRLOja

**Comment by eternalsky** [comment]
Search 中 jsxshowLabel 默认是 false

**Comment by wushanchao** [comment]
文档中应该加上Search的jsxshowLabel为false

**Comment by eternalsky** [comment]
@wushanchao 恩，后续加上
