### ISSUE TITLE
SearchFormField宽度自适应问题

### ISSUE THREAD

**Issue by luohuasen** [uxcore/uxcore-form#108]
InputFormField，SelectFormField，BuouField都能自适应页面宽度，但是SearchFormField无法自适应，DateFormField可以自适应，但是样式出错
demo地址  http://codepen.io/sethLuo/pen/pbVKwP

**Comment by eternalsky** [comment]
InputFormField，SelectFormField，BuouField 是因为其展示内容单一，只有一个输入框，级联和搜索都偶有多个区块是固定宽度的，请根据业务需求，加专属类名进行样式覆盖。很多时候，自适应反而并不是对这些块的要求。
