### ISSUE TITLE
清空form的校验错误信息

### ISSUE THREAD

**Issue by shallker** [uxcore/uxcore-form#114]
允许doValidate()返回一个恒定为true的检验结果，并清空错误信息。

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-form-field/commit/5b2387137aa4c693b1828f92d4e691ef43e13e71

fix in https://github.com/uxcore/uxcore-form/commit/00c161a6fb27c625b4ad7b5ace4581c9366873eb

doValidate(true, true)
