### ISSUE TITLE
为什么Form组件不能捕捉到Enter按键

### ISSUE THREAD

**Issue by WClouds** [uxcore/uxcore-form#116]
为什么uxcore-form不能在Form上使用onSubmit={this.handleSubmit}，
以及在Button上使用type="submit"，来使用Enter按键提交表单？？
虽然我有看到ButtonGroupFormField里有一个action属性，但是好像没有什么作用啊。
我该如何使用Enter按键提交表单呢？？

**Comment by WClouds** [comment]
好吧，我知道了，原来还要在Form组件外面再包一层form

**Comment by eternalsky** [comment]
如果想要在 InputFormField 上通过通过Enter来完成提交，可以在 InputFormField 上监听 onKeyDown

**Comment by WClouds** [comment]
恩，好的，谢谢
