### ISSUE TITLE
EditorFormField渲染报错且无法读取props.jsxcontent改变后的值

### ISSUE THREAD

**Issue by ex90rts** [uxcore/uxcore-form#118]
rt，渲染报错基本定位到EditorFormField.componentWillReceiveProps -> handleDataChange 传参错误；再次渲染props.jsxcontent改变后，新值无法渲染到tinymce里面待查

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-form/commit/e9ab7147cd704b95f21c16808fd6f9eba5c203c9
