### ISSUE TITLE
InputFormField、TextAreaFormField计数器功能能否优化单独设置字数样式

### ISSUE THREAD

**Issue by digitaloceanwork** [uxcore/uxcore-form#125]
在使用计数器功能的时候，因为需求需要对超出的数字部分单独设置红色样式，现在组件是生成了一个包含当前数字和总数字的整体，无法单独设置样式，详情如下图所示：
![image](https://cloud.githubusercontent.com/assets/3124551/21525047/88204e9e-cd55-11e6-9f82-11ee97e7b0ef.png)
![image](https://cloud.githubusercontent.com/assets/3124551/21525068/aa70a354-cd55-11e6-93e6-c3c1fd4ebfef.png)

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-textarea-form-field/commit/8e947da1f809570544d3c872f33b8f66d9ba33f7
https://github.com/uxcore/uxcore-input-form-field/commit/b1fb6d4cb5136f16d723999ed725f7682ce1e4e2
