### ISSUE TITLE
NumberInputFormField为money且delimiter为空时格式化数值不正确

### ISSUE THREAD

**Issue by jzlingmo** [uxcore/uxcore-form#126]
```
<NumberInputFormField jsxtype="money" />
```

以上设置delimiter为空，格式化时uxcore-formatter中`delimiter = delimiter || " ";`用的空格，去除格式时deFormatValue中用的是this.props.delimiter(为空)，两者不一致

**Comment by eternalsky** [comment]
uxcore-formatter 改为只在 delimeter 为 undefined 使用默认值

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-formatter/commit/6a05bfdd31cf119e99c0179080a53ecbecaaf56e
