### ISSUE TITLE
EditorFormField第一次给form setValues后  第二次setValues不同的值的时候还是显示第一次的值，其他的form子组件都是可以的

### ISSUE THREAD

**Issue by shaojun427** [uxcore/uxcore-form#127]
http://codepen.io/zhoushaojun427/pen/rjmwQB
上面是复现地址，输入框先输入一段内容打开form之后， 再改变输入框内容，再打开form，input的值变了，富文本没变

**Comment by eternalsky** [comment]
上面的 Demo 中，并没有用到 如之前沟通的 Form API setValues ，如果是通过 jsxValues 修改无效的话，这个是预期内的行为，原因之前也已经沟通过。再附链接如下：

https://github.com/uxcore/uxcore-form#api-1
