### ISSUE TITLE
CheckboxGroupFormField.Item 的个数如果小于两个，form 在 View 状态下就会报错

### ISSUE THREAD

**Issue by FE-Girl** [uxcore/uxcore-form#132]
![image](https://cloud.githubusercontent.com/assets/6926706/23640387/3490c21e-0328-11e7-8d4d-99f50dabd8e9.png)

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-form/commit/c2f6c0cc3f79705ed64a3bd647f50035c31bf8eb
