### ISSUE TITLE
是否有访问权限啊? 

### ISSUE THREAD

**Issue by HuiguangChu** [uxcore/uxcore-form#134]
![conecttion_problem](https://cloud.githubusercontent.com/assets/3482267/23816980/2ecf85a2-05f0-11e7-9c9f-b39043ec7f6a.JPG)

**Comment by HuiguangChu** [comment]
确定是http而不是https？

**Comment by HuiguangChu** [comment]
![conecttion_problem](https://cloud.githubusercontent.com/assets/3482267/23817284/3c775246-05f2-11e7-8692-46f0e6743397.JPG)
插件load 404 @eternalsky @yanbingbing @majorye @macisi

**Comment by eternalsky** [comment]
访问权限是有的，可能是运营商劫持。我们已经改成默认使用 https 链接。https://github.com/uxcore/uxcore-tinymce/commit/ce3229cb81bfa047396d5323ed634584d78ebf5c 当然，你也可以自定义配置，去覆盖这些配置~

**Comment by HuiguangChu** [comment]
bugs:

1. initial 不到，tynumce不是应该在这个component里面就应该被imported的么？ 如果不单独安装 tinymce 然后与uxore-tinymce一同引入到同一个compoennt下则会报错： this.window.tinymce is not defined.      

2. 插件还是load不到, 只能import from tinymce 所有要用的插件直至没有错误，相当的麻烦。 @eternalsky

**Comment by HuiguangChu** [comment]
![error](https://cloud.githubusercontent.com/assets/3482267/23850499/0ab5fbb4-07e0-11e7-80a2-fa585c48c58c.jpg)
![plugin error](https://cloud.githubusercontent.com/assets/3482267/23850498/0ab59782-07e0-11e7-9288-8103b1d46ab8.JPG)

**Comment by eternalsky** [comment]
组件目前不做自动 import，有需要的情况下，请在页面上直接引入~ plugin 引入不到，是因为第一个问题。
baseUrl 没有设置成功。

**Comment by eternalsky** [comment]
reopen it if neccesary
