### ISSUE TITLE
jsxvalues 变化或者 setValues 的情况下会触发校验

### ISSUE THREAD

**Issue by eternalsky** [uxcore/uxcore-form#140]
目前这些非用户操作的变化，是不会触发 onChange 操作的，但是仍会触发校验，是否合理？点赞表示合理，反对表示不合理

**Comment by FE-Girl** [comment]
反对校验

**Comment by eternalsky** [comment]
@FE-Girl 可以点首楼上面的笑脸 icon 来投票~

**Comment by jianfei** [comment]
我觉得getValues默认也不应该触发校验....

**Comment by eternalsky** [comment]
@jianfei 点击确认时触发校验一般还是符合预期的，不想校验的情况下可以关闭~

**Comment by beeant0512** [comment]
有人知道怎么手动设置某字段校验失败嘛？ 在ajax success返回的时候设置某个字段校验失败，提醒内容是后端返回的

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-form-field/commit/d0ac04ab90af9a67e6659146c2eff265037ce926
