### ISSUE TITLE
请问使用哪个api可以设置input校验失败

### ISSUE THREAD

**Issue by beeant0512** [uxcore/uxcore-form#141]
比如 ajax提交的form，后端根据传递的一系列参数进行业务处理，然后返回某个字段有问题，这种场景下怎么吧这个错误消息设置到对于的input

**Comment by eternalsky** [comment]
你说的应该是 异步校验，form 中有 `asyncValidate` 去开启异步校验，具体 demo，可以看：https://github.com/uxcore/uxcore-form/blob/master/demo/FormDemoAsync.jsx

**Comment by beeant0512** [comment]
@eternalsky 还不仅仅是异步校验，可能是我的理解不够或表达不清楚， 是这样的场景：页面上有3个输入框 input1,intpu2,intpu3，然后表单提交，后端返回input1,intpu2值无效（举例），这样该如何实现？请问有没有api可以设置使某个input失效的方法

**Comment by eternalsky** [comment]
这个比异步校验更简单，首先你可以设置表单 非即时校验，instantValidate = false，然后可以在你的数据提交上去之后等数据回来，再调用 isDirty 或者 doValidate 方法，进行校验。

**Comment by beeant0512** [comment]
@eternalsky 能不能给个示例 确实没有搞明白怎么弄。  以下是我这边的代码：

_class LoginForm extends React.Component {

    constructor(props) {
        super(props);
        this.state = {};

        this.handleClick = this.handleClick.bind(this);
    }

    saveRef(refName) {
        const me = this;
        return (c) => {
            me[refName] = c;
        };
    }

    handleClick() {

        let _this = this;
        let formValues = this.form.getValues();
        if (formValues.pass) {
            Request
                .post(ctp + '/login')
                .type('form')
                .send(formValues.values)
                .set('X-CSRF-TOKEN', csrf)
                .end(function (err, res) {
                    if (err) {
                        //do something
                    } else {
                        // if (1 == res.body.code) {
                       //  例如： 密码错误， 该怎么把错误消息给pwd input
                        _this.form.doValidate();
                        // }
                    }
                })
        }
    }

    render() {
        let me = this;
        return (
            <div className="kuma-container-full">
                <div className="login">
                    <style>
                        {".required {font-family:Simsun} " +
                        ".login-form {width: 532px;width: 532px;margin: auto;top: 100px;position: relative;}"}
                    </style>
                    <Form ref={this.saveRef('form')} className="login-form" instantValidate={false}>
                        <Input jsxname="usr" jsxlabel="用户名" autoTrim="true" jsxplaceholder="请输入用户名"
                               required={true}
                               jsxrules={[
                                   {validator: Validators.isNotEmpty, errMsg: "用户名不能为空"}]}/>
                        <Input jsxname="pwd" jsxlabel="密码" inputType="password" autoTrim="true"
                               jsxplaceholder="请输入密码"
                               required={true}
                               jsxrules={[
                                   {validator: Validators.isNotEmpty, errMsg: "密码不能为空"}]}/>
                        <Other>
                            <Button style={{marginLeft: '88px'}} onClick={this.handleClick}>登录</Button>
                        </Other>
                    </Form>
                </div>
            </div>
        )

    }
}_

**Comment by eternalsky** [comment]
> validator 也可以自己定义，会传入相应的表单值，根据判断，返回 true，表示通过。

一些变量，你可以在你的 store 里存储，比如 errMsg 里的内容，比如 validator 函数用于校验是否通过的变量。

```
...
else {
this.setState({ errMsg: xxx, isError: xxx}, () => {this.form.doValidate()})
}
...
```

这其实跟组件用法已经没关系了，关键是你要想明白操作的顺序，其实你已经想复杂了

**Comment by beeant0512** [comment]
@eternalsky 才接触react所以很多地方还不懂，不知道方不方便加Q或微信（以邮件），多向你请教一下。

**Comment by beeant0512** [comment]
@eternalsky 试了你提供的代码，没有达到效果。

以下代码也没有实现效果。
_this.form.fields.pwd.setState({ errMsg: 'xxx', isError: 'xxxxx'}, () => {false})

**Comment by eternalsky** [comment]
@beeant0512 我那个只是一个用来说明意图的伪代码，不是直接 copy 上去就能用的，你要先明白我表达的是什么意思~

**Comment by eternalsky** [comment]
非组件问题，不在 issue 中做更深入讨论，如果有 react 的使用疑问，请去 SegmentFault 上进行提问。可以在 SF 上标记 uxcore tag 进行提问。
