### ISSUE TITLE
EditorFormField为readonly状态时setContent报错

### ISSUE THREAD

**Issue by eJayYoung** [uxcore/uxcore-form#156]
[https://github.com/uxcore/uxcore-form/blob/master/src/FormField/EditorFormField.jsx#L55](https://github.com/uxcore/uxcore-form/blob/master/src/FormField/EditorFormField.jsx#L55)

解决方案：
加个非空判断
```
setContent(content) {
  this.tinymce && this.tinymce.resetValue(content);
}
```

**Comment by eternalsky** [comment]
能说一下 ReadOnly 下还会 setContent 的场景吗~

**Comment by eJayYoung** [comment]
我是在使用乐高搭的项目，
场景是：一个dialog里面展示一些只能readonly的form，在关掉dialog的时候会触发setContent报错

**Comment by eternalsky** [comment]
那修改策略，应该是判断一下，只有在 edit 的情况下才会真正调用 this.tinymce.resetValue
