### ISSUE TITLE
是否应去掉 prop 中的 jsx 前缀？

### ISSUE THREAD

**Issue by eternalsky** [uxcore/uxcore-form#18]
1、jsx 并没有 uxcore 的表意性。
2、jsx 会增加写 prop 和记 prop 的成本。
3、事实上大部分组件没有加 jsx 前缀，包括 grid，目前只有 form 是基本加 jsx 的。
4、基于上一条原因，使得我们在使用其他组价和 form 的类似功能时，会出现 api 有所差异的问题，容易被人吐槽，事实上已经被 peng2e 吐槽了。

**Comment by bshy522** [comment]
我想知道为什么要加这个jsx呢?  有什么特殊含义吗?

**Comment by majorye** [comment]
@bshy522  是遵循了  [GI](http://www.generalinterface.org/) 的规范，我们内部也在讨论，但如果后续要做 IDE来满足 企业级产品开发，我还是建议 保留。 

目前IDE正在研发中，12月中，我们会决定 jsx前缀的去留

**Comment by eternalsky** [comment]
Final decision: remove jsx prefix in future ver
