### ISSUE TITLE
提供一个跟 getValues方法一样的走非validate的数据

### ISSUE THREAD

**Issue by peng2e** [uxcore/uxcore-form#22]
情景如下，如果动态改变rule 比较麻烦，如果能提供一个 方法 返回所有数据 且不验证会比较方便。
比如 我要保存一个form 这个form 可以不验证， 动态改变比较麻烦~~

@eternalsky

**Comment by eternalsky** [comment]
关键是你输入的时候，他就已经开始 validate 了

**Comment by gbk** [comment]
validate 包括强制校验和可容忍校验，强制校验不通过的话不允许保存，可容忍校验不通过的话仍可保存。

强制校验适用的场景：输入超长（提交后数据库会报错），其他一些可能引起逻辑异常的必填项
可容忍校验适用场景：必填校验、正则校验

**Comment by eternalsky** [comment]
目前的解决方案是 提供 FORM 级和 FORMFIELD 级 两级的是否开启实时检测的 prop，提供新 API，返回数据但不做校验（返回格式与 getValues 相同）
