### ISSUE TITLE
针对form 提供setData方法 ，这样可以针对onChange的时候，动态该表某一个formField的值

### ISSUE THREAD

**Issue by peng2e** [uxcore/uxcore-form#30]

**Comment by peng2e** [comment]
这个setData 希望是一个 json 
eg:  一个 checkbox  ， 一个select。 select发生变化 ，set checkbox的data
checkbox:{
   value: 111,
   checkbox: disabled,
   className: 'hello'
 ......
}

只要 formField有的属性，都可以 set....

**Comment by eternalsky** [comment]
只能setValues，因为只有 value 是 Form 内部 state 管理的，其他的都是外部 prop 传入
