### ISSUE TITLE
table分页bug，删除当前分页的最后一条数据，页面数据显示为空

### ISSUE THREAD

**Issue by robin71** [uxcore/uxcore-form#40]
【操作步骤】：
1、当前页面存在21条数据，将页面翻到第三页后
2、将最后一条数据删除
【期望结果】：返回到分页的第一页，并且展示第一页的数据
【实际结果】：页面显示无数据

**Comment by eternalsky** [comment]
https://github.com/uxcore/uxcore-table/tree/master/src 请提到 table里，另请具体说明删除操作的用法
