### ISSUE TITLE
inputformfield增加支持password的输入

### ISSUE THREAD

**Issue by vincentshow** [uxcore/uxcore-form#71]
form组件的input是否也能给出一个jsxtype属性来控制input的type，官方示例中缺少一个type=password的组件，或者出一个PasswordFormField

**Comment by eternalsky** [comment]
Form 提供自定义扩展 FormField 的能力，可以看这里：http://uxco.re/scene/commonForm/#code-box-scene-commonform-demo-definefield

**Comment by vincentshow** [comment]
感谢
