### ISSUE TITLE
Form VIEW 模式传入的jsxvalues  如果是{} / null  会报错，希望处理逻辑同 EDIT模式

### ISSUE THREAD

**Issue by peng2e** [uxcore/uxcore-form#72]
设计的时候就是考虑到 一个 MODE 作为开关即可实现 view/ edit 的切换， 目前看来 selectFormField 的处理有点小问题。

**Comment by peng2e** [comment]
设计的时候就是考虑到 一个 MODE 作为开关即可实现 view/ edit 的切换， 目前看来 selectFormField 的处理有点小问题。

**Comment by eternalsky** [comment]
same as #70，传 null 肯定是不行的，会支持传{}
