### ISSUE TITLE
Form不支持回车自动提交

### ISSUE THREAD

**Issue by vincentshow** [uxcore/uxcore-form#76]
看了下源码，生成的html容器是div，不是form，导致我用Form做的登陆页面无法回车自动提交，也无法使用浏览器的自动完成或者记住用户名和密码功能，有其他方案么，求指点

**Comment by eternalsky** [comment]
恩，Form 使用更解耦的方式来完成这件事的，首先 Form 里面可以通过 getValues 的 API 拿到全部的值，所以你可以选择在你想要提交的时机获取到所有要提交的值，例如你说的情况，你可以在 Form 的外层容器上监听回车按下去的事件。自动补全的功能目前确实不行了。

**Comment by vincentshow** [comment]
好吧，目前也只能这样了

**Comment by eternalsky** [comment]
增加 keycode 配置
