### ISSUE TITLE
使用webpack打包报错Error: ENOENT: no such file or directory, open 'src\node_modules\react\lib\EventListener.j s' at Error (native)  @ ./~/react/lib/ReactEventListener.js 

### ISSUE THREAD

**Issue by vincentshow** [uxcore/uxcore-form#81]
这个是react报的错应该和uxcore没有多大关系，但是我的package.json中有关react的依赖是复制uxcore-form这个项目里的配置，一打包就报错
1. 我尝试把react改成react-addons，更加不行了，后来还是改回react，只能手动把缺失的文件从addons复制到react中
2. 这次react不报错了，浏览器里运行，TextAreaFormField等几个FormField子类又报React未定义错误，我手动修改这些文件，把React引用加进去
3. 运行后，原来的错误消失，又出现React.addons未定义错误...彻底没思路了
后端刚转前端，菜鸟一个，还请大神指点下

**Comment by vincentshow** [comment]
这些和我打包的配置文件有关系么，我的webpack配置
var webpack = require('webpack');
module.exports = {
    entry: [
      'webpack/hot/only-dev-server',
      "./js/app.js"
    ],
    output: {
        path: './build',
        filename: "bundle.js"
    },
    module: {
        loaders: [
            { test: /.jsx$/, exclude: /node_modules/, loaders: ['react-hot', 'babel'] },
            { test: /.js$/, exclude: /node_modules/, loader: 'babel-loader'},
            { test: /.css$/, loader: "style!css" }
        ]
    },
    resolve:{
        extensions:['','.js','.jsx','.json']
    },
    plugins: [
      new webpack.NoErrorsPlugin()
    ]
};

**Comment by eternalsky** [comment]
要避免 React 在页面有两个实例产生的情况，一般我们的处理方式是在全局引入一个 react.js，在 webpack 的配置中用 externals，把 React 和 ReactDOM 引向全局变量。
···
externals: {
        react: 'var React', // 相当于把全局的React作为模块的返回 module.exports = React;
        'react-dom': 'var ReactDOM'
    },
···
