### ISSUE TITLE
除了用户主动的Change事件，屏蔽掉其他内部change事件。

### ISSUE THREAD

**Issue by peng2e** [uxcore/uxcore-form#82]
内部事件的change可能会触发field 本身的change时间，这个事件并不是我想要的，用户主动事件做的事，用户自己掌控，内部事件自己消化。

**Comment by eternalsky** [comment]
目前需要修改的点，包括 setValues, resetValues, componentWillReceiveProps，所有的 formfield 要支持 setValue 接口，如果是直接继承没有修改的，应该直接可用。

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-form/commit/29efeb906c0c8b277caf392c102449de591d0070
