### ISSUE TITLE
SelectFormField: jsxdata 的传值支持数组

### ISSUE THREAD

**Issue by alex-mm** [uxcore/uxcore-form#84]
selectField value如果为数字，默认选中有问题

**Comment by eternalsky** [comment]
与 jsxdata 的传值方式有关，后续考虑增加 jsxdata 的传值支持数组

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-select-form-field/commit/9a225c69a57ce08647fafea4afa30c541f9fa3c1
