### ISSUE TITLE
Select 有onsearch 方法的希望在getValues的时候可以直接返回obj.key 

### ISSUE THREAD

**Issue by peng2e** [uxcore/uxcore-form#98]

**Comment by eternalsky** [comment]
这个没有办法，我也需要里面的 label 数据去正确显示，如果只给你 key，那么你把那个值传回给我，我就无法正确展示没有选项的值了。

**Comment by peng2e** [comment]
get 只是需要一个value ，通过obj.key获取方式很挫，至少使用方式不同于其他的formField。如果是set的话可以setobj没问题的。

**Comment by eternalsky** [comment]
@peng2e 不只是 set 的问题，比如要使用受限模式把 onChange 的内容和 jsxvalues 关联上，只传 value 是不够的，以前是 label 分开的，现在 label 在 value 里，必须得用这种方式才行，实际上有很多人反映希望能在获取 key 的同时，获取 label。

**Comment by peng2e** [comment]
其他模式我并不care 只是在getValues的时候如果能返回这个key那就是极好的。 获取到数据后这个Field单独处理总是觉得怪怪的。

**Comment by qq7892326** [comment]
同提

**Comment by eternalsky** [comment]
不同人群需求不一致，维持原状，如果有好的想法，可以重提 issue
